
const products = [
     // Kids Clothing
     {
          id: 1,
          name: "Boys & Girls Full Sleeve Self Design Hooded Sweatshirt",
          category: "kids",
          imgUrl: "https://rukminim2.flixcart.com/image/612/612/xif0q/sweatshirt/8/q/1/3-4-years-quanthoody-emblica-original-imah4ufyjytcff8j.jpeg?q=70",
          newPrice: 409,
          oldPrice: 1999,
     },
     {
          id: 2,
          name: "Boys Casual T-shirt Track Pants  (Wine)",
          category: "kids",
          imgUrl: "https://rukminim2.flixcart.com/image/612/612/xif0q/kids-apparel-combo/m/t/7/3-4-years-t-f22-wine-space-mars-infiniti-original-imaghhc5rbpddnrz.jpeg?q=70",
          newPrice: 242,
          oldPrice: 900,
     },
     {
          id: 3,
          name: "Boys & Girls Casual T-shirt Pant  (Olive)",
          category: "kids",
          imgUrl: "https://rukminim2.flixcart.com/image/612/612/xif0q/kids-apparel-combo/i/0/n/4-5-years-ctc002-cute-n-tight-original-imagqkp8y3cdnfbz.jpeg?q=70",
          newPrice: 180,
          oldPrice: 599,
     },
     {
          id: 4,
          name: "Boys Festive & Party Kurta and Pyjama Set  (Maroon Pack of 1)",
          category: "kids",
          imgUrl: "https://rukminim2.flixcart.com/image/612/612/xif0q/kids-ethnic-set/0/2/m/1-2-years-kurta-01simple-rvson-original-imah5xyhzeygfkdn.jpeg?q=70",
          newPrice: 380,
          oldPrice: 1099,
     },
     {
          id: 5,
          name: "Boys Festive & Party Kurta and Dhoti Pant Set  (Blue Pack of 1)",
          category: "kids",
          imgUrl: "https://rukminim2.flixcart.com/image/612/612/xif0q/kids-ethnic-set/v/y/l/3-4-years-printed-dhoti-kurta-rcensa-original-imah6ymnxyceduub.jpeg?q=70",
          newPrice: 499,
          oldPrice: 1299,
     },
     {
          id: 6,
          name: "Boys Festive & Party Kurta and Pyjama Set  (Multicolor Pack of 1)",
          category: "kids",
          imgUrl: "https://rukminim2.flixcart.com/image/612/612/xif0q/kids-ethnic-set/j/5/m/11-12-years-digital-multicolor11-12-madhavart-original-imagyt8rwsagh6mm.jpeg?q=70",
          newPrice: 499,
          oldPrice: 999,
     },
     {
          id: 7,
          name: "Boys Regular Fit Self Design Spread Collar Casual Shirt",
          category: "kids",
          imgUrl: "https://rukminim2.flixcart.com/image/612/612/xif0q/shirt/t/d/e/12-13-years-kids-pop-white-vtexx-original-imah3h8wzhe2jc55.jpeg?q=70",
          newPrice: 499,
          oldPrice: 1599,
     },
     {
          id: 8,
          name: "Short For Boys Casual Printed Cotton Blend  (Dark Green, Pack of 5)",
          category: "kids",
          imgUrl: "https://rukminim2.flixcart.com/image/612/612/xif0q/kids-short/0/b/u/9-10-years-hft-h5s23-ol2-icj-cdg-na3-bu1-hellcat-original-imagnfw8asfhrsbv.jpeg?q=70",
          newPrice: 699,
          oldPrice: 2999,
     },
     {
          id: 9,
          name: "Boys Graphic Print Cotton Blend Oversized T Shirt",
          category: "kids",
          imgUrl: "https://rukminim2.flixcart.com/image/612/612/xif0q/kids-t-shirt/5/n/u/15-16-years-togrrnosboy-bd129-tripr-original-imahytgxcydvrczs.jpeg?q=70",
          newPrice: 299,
          oldPrice: 1999,
     },
     {
          id: 10,
          name: "Boys Printed Cotton Blend Regular T Shirt  (Light Blue, Pack of 3)",
          category: "kids",
          imgUrl: "https://rukminim2.flixcart.com/image/612/612/xif0q/kids-t-shirt/c/i/o/9-10-years-hft-23hr3-pe-ics-br-hellcat-original-imagn9wcvmrpbjdz.jpeg?q=70",
          newPrice: 499,
          oldPrice: 2999,
     },
     {
          id: 11,
          name: "Boys Striped Pure Cotton Regular T Shirt  (Dark Blue, Pack of 1)",
          category: "kids",
          imgUrl: "https://rukminim2.flixcart.com/image/612/612/xif0q/kids-t-shirt/0/k/f/7-8-years-peb9376-bumzee-original-imagze93rkhg7ktj.jpeg?q=70",
          newPrice: 499,
          oldPrice: 1099,
     },
     {
          id: 12,
          name: "Baby Boys & Baby Girls Printed Polycotton Regular T Shirt",
          category: "kids",
          imgUrl: "https://rukminim2.flixcart.com/image/612/612/xif0q/kids-t-shirt/m/h/f/9-10-years-free-fire-kids-half-sleeve-tshirt-avr-original-imah6ftsb4wc7e4y.jpeg?q=70",
          newPrice: 299,
          oldPrice: 699,
     },

     // Men's Clothing
     {
          id: 13,
          name: "Solid Men Polo Neck Poly Cotton Black T-Shirt",
          category: "mens",
          imgUrl: "https://rukminim2.flixcart.com/image/612/612/xif0q/shopsy-t-shirt/f/m/b/xl-polo-tshirt-2-combo-leemak-original-imah3yw5khygszxt.jpeg?q=70",
          newPrice: 299,
          oldPrice: 1999,
     },
     {
          id: 14,
          name: "Men Slim Mid Rise Black Jeans",
          category: "mens",
          imgUrl: "https://rukminim2.flixcart.com/image/612/612/xif0q/jean/z/r/0/40-hpsjoggerball-black-urbano-fashion-original-imafu9hqvbuzxhgz-bb.jpeg?q=70",
          newPrice: 703,
          oldPrice: 1799,
     },
     {
          id: 15,
          name: "Men Regular Fit Striped Formal Shirt",
          category: "mens",
          imgUrl: "https://rukminim2.flixcart.com/image/612/612/xif0q/shirt/k/8/g/m-r-black-stoneberg-original-imah4rquzsggpwjg.jpeg?q=70",
          newPrice: 299,
          oldPrice: 999,
     },
     {
          id: 16,
          name: "Men Solid Hooded Neck Multicolor Sweater",
          category: "mens",
          imgUrl: "https://rukminim2.flixcart.com/image/612/612/xif0q/sweater/n/j/o/xxl-men-plain-hoody-sweatshirt-navy-arrone-original-imagg8jydd2fwkqw.jpeg?q=70",
          newPrice: 479,
          oldPrice: 1545,
     },
     {
          id: 17,
          name: "Men Full Sleeve Color Block Hooded Sweatshirt",
          category: "mens",
          imgUrl: "https://rukminim2.flixcart.com/image/612/612/jvv9zm80/sweatshirt/g/h/z/xxl-4453178-hrx-by-hrithik-roshan-original-imafgzseazfuzhpg.jpeg?q=70",
          newPrice: 840,
          oldPrice: 2599,
     },
     {
          id: 18,
          name: "Men Jogger Fit Mid Rise Dark Blue Jeans",
          category: "mens",
          imgUrl: "https://rukminim2.flixcart.com/image/612/612/xif0q/jean/a/d/v/32-z-jog-05-zaysh-original-imah2ur7c39azc4c.jpeg?q=70",
          newPrice: 499,
          oldPrice: 1299,
     },
     {
          id: 19,
          name: "Men Solid Denim Jacket",
          category: "mens",
          imgUrl: "https://rukminim2.flixcart.com/image/612/612/xif0q/jacket/j/i/c/xl-1-no-536-1-ftx-original-imagx7ntzxab4y5n.jpeg?q=70",
          newPrice: 799,
          oldPrice: 2199,
     },
     {
          id: 20,
          name: "Men Slim Fit Black Cotton Blend Trousers",
          category: "mens",
          imgUrl: "https://rukminim2.flixcart.com/image/612/612/xif0q/trouser/m/j/w/32-kctr-dmy-2121-bk-fubar-original-imahyefvtpvhjbp7.jpeg?q=70",
          newPrice: 499,
          oldPrice: 1599,
     },
     {
          id: 21,
          name: "Men Solid Leather Jacket",
          category: "mens",
          imgUrl: "https://rukminim2.flixcart.com/image/612/612/xif0q/jacket/x/8/r/s-1-no-ltr-singlezip-hmd-fashion-point-original-imah4yrky39agwzv.jpeg?q=70",
          newPrice: 1799,
          oldPrice: 3099,
     },
     {
          id: 22,
          name: "Men Striped V Neck Blue Sweater",
          category: "mens",
          imgUrl: "https://rukminim2.flixcart.com/image/612/612/xif0q/sweater/k/l/w/xxl-muskvneckmanyrecnavy-nico-wesley-original-imah6ghnbxzdazwn.jpeg?q=70",
          newPrice: 499,
          oldPrice: 2299,
     },
     {
          id: 23,
          name: "Solid Men Polo Neck Cotton Blend Dark Green T-Shirt",
          category: "mens",
          imgUrl: "https://rukminim2.flixcart.com/image/612/612/xif0q/t-shirt/b/j/7/xxl-mt1007pr-metronaut-original-imahygvag2wfeduw.jpeg?q=70",
          newPrice: 249,
          oldPrice: 1699,
     },
     {
          id: 24,
          name: "Men Cargo Pants",
          category: "mens",
          imgUrl: "https://rukminim2.flixcart.com/image/612/612/xif0q/cargo/q/s/8/s-togrjog-dp5-cargo19-tripr-original-imah5jcbwfhyypdn.jpeg?q=70",
          newPrice: 599,
          oldPrice: 2099,
     },
     // Women's Clothing
     {
          id: 25,
          name: "Women Tiered Pink Dress",
          category: "womens",
          imgUrl: "https://rukminim2.flixcart.com/image/612/612/xif0q/dress/8/n/5/s-sn030-s-n-studio-original-imagmxf36pcabphv.jpeg?q=70",
          newPrice: 499,
          oldPrice: 1999,
     },
     {
          id: 26,
          name: "Women Regular High Rise Grey Jeans",
          category: "womens",
          imgUrl: "https://rukminim2.flixcart.com/image/612/612/xif0q/jean/e/k/r/36-fwaw24jen245-flying-machine-original-imahf3f3gzfwdfdg.jpeg?q=70",
          newPrice: 2299,
          oldPrice: 2399,
     },
     {
          id: 27,
          name: "Women Solid Single Breasted Casual Blazer  (Black)",
          category: "womens",
          imgUrl: "https://rukminim2.flixcart.com/image/612/612/xif0q/blazer/z/l/r/xxl-kttwomensblazer42-kotty-original-imahfgxyd7hxtj4e.jpeg?q=70",
          newPrice: 299,
          oldPrice: 1999,
     },
     {
          id: 28,
          name: "Women Printed Hooded Neck Multicolor Sweater",
          category: "womens",
          imgUrl: "https://rukminim2.flixcart.com/image/612/612/xif0q/sweater/e/9/j/xl-women-blessed-swetshirt-black-wearspot-original-imagg44pzbv8cwfc.jpeg?q=70",
          newPrice: 499,
          oldPrice: 1599,
     },
     {
          id: 29,
          name: "Women Floral Print Regular Black Skirt",
          category: "womens",
          imgUrl: "https://rukminim2.flixcart.com/image/612/612/xif0q/skirt/z/t/g/free-black-varanga-fashioncutz-original-imafvp7phkrftdwv-bb.jpeg?q=70",
          newPrice: 399,
          oldPrice: 1699,
     },
     {
          id: 30,
          name: "WOOL Self Design Coat For Women",
          category: "womens",
          imgUrl: "https://rukminim2.flixcart.com/image/612/612/xif0q/coat/e/r/h/xl-card-hair-black-young-threads-collection-original-imagj7d9jj6mjtmt.jpeg?q=70",
          newPrice: 499,
          oldPrice: 1999,
     },
     {
          id: 31,
          name: "Casual Regular Sleeves Solid Women Maroon Top",
          category: "womens",
          imgUrl: "https://rukminim2.flixcart.com/image/612/612/xif0q/top/g/m/a/s-1-501-maroon-sm-unifringe-original-imahfk5zmrujtpyu.jpeg?q=70",
          newPrice: 299,
          oldPrice: 699,
     },
     {
          id: 32,
          name: "Women Flared Black Viscose Rayon Trousers",
          category: "womens",
          imgUrl: "https://rukminim2.flixcart.com/image/612/612/xif0q/trouser/u/a/y/34-kttwomenspant324-kotty-original-imagmycpeswzfgfy.jpeg?q=70",
          newPrice: 399,
          oldPrice: 1999,
     },
     {
          id: 33,
          name: "Casual Regular Sleeves Printed Women Brown",
          category: "womens",
          imgUrl: "https://rukminim2.flixcart.com/image/612/612/xif0q/shopsy-top/q/h/s/xl-shopsyt-printed-indigo-tiger-dream-beauty-fashion-original-imagvcrbhuza5tva.jpeg?q=70",
          newPrice: 299,
          oldPrice: 999,
     },
     {
          id: 34,
          name: "Women Pleated Dark Green Dress",
          category: "womens",
          imgUrl: "https://rukminim2.flixcart.com/image/612/612/kylvr0w0/dress/r/c/8/xl-515-platingdress-green-xl1-deklook-original-imagatyqz79twqbx.jpeg?q=70",
          newPrice: 499,
          oldPrice: 1999,
     },
     {
          id: 35,
          name: "Round Neck Women Blouse",
          category: "womens",
          imgUrl: "https://rukminim2.flixcart.com/image/612/612/xif0q/blouse/j/s/d/free-f-wht-hakoba-subhadra-creation-house-original-imah2auqtzefc5ea.jpeg?q=70",
          newPrice: 299,
          oldPrice: 999,
     },
     {
          id: 36,
          name: "Women Solid Denim Jacket",
          category: "womens",
          imgUrl: "https://rukminim2.flixcart.com/image/612/612/ktaeqvk0/jacket/a/d/d/xl-no-z517-m-moddy-original-imag6z4ygy6zwy55.jpeg?q=70",
          newPrice: 599,
          oldPrice: 1299,
     },
     {
          id: 37,
          name: "Floral Print Women Track Suit",
          category: "womens",
          imgUrl: "https://rukminim2.flixcart.com/image/612/612/xif0q/night-suit/l/3/j/l-s36-night-dress-for-women-night-suits-for-ladies-pyjama-set-original-imah3kfwystdzsfz.jpeg?q=70",
          newPrice: 449,
          oldPrice: 1999,
     },
     {
          id: 38,
          name: "Colorblock Women Track Suit",
          category: "womens",
          imgUrl: "https://rukminim2.flixcart.com/image/612/612/xif0q/track-suit/7/c/8/l-co-zara-dtr-fashion-original-imah46msmn7hmzgx.jpeg?q=70",
          newPrice: 449,
          oldPrice: 1999,
     },
     {
          id: 39,
          name: "Women Solid Round Neck Polyester Blue T-Shirt",
          category: "womens",
          imgUrl: "https://rukminim2.flixcart.com/image/612/612/krayqa80/t-shirt/5/d/l/xxl-dsw0909-dsws-original-imag54d5f62svjxr.jpeg?q=70",
          newPrice: 247,
          oldPrice: 799,
     },
     {
          id: 40,
          name: "Striped Women Track Suit",
          category: "womens",
          imgUrl: "https://rukminim2.flixcart.com/image/612/612/xif0q/track-suit/6/x/c/xxl-r4-db-astin-dtr-fashion-original-imagz273mhmwdnbv.jpeg?q=70",
          newPrice: 499,
          oldPrice: 2999,
     },
]

export default products;